export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
      extend: {
          "colors": {
              "surface-container-high": "#e5e9eb",
              "surface-container-lowest": "#ffffff",
              "on-secondary-fixed": "#24434f",
              "surface-dim": "#d5dbdd",
              "secondary-container": "#c7e8f6",
              "on-secondary": "#f2faff",
              "on-tertiary-fixed": "#003e39",
              "on-surface-variant": "#5a6062",
              "error-dim": "#67040d",
              "primary-fixed": "#85d7f9",
              "primary-container": "#85d7f9",
              "on-secondary-container": "#375662",
              "on-primary-fixed-variant": "#00546b",
              "on-error-container": "#6e0a12",
              "background": "#f8f9fa",
              "on-surface": "#2d3335",
              "on-background": "#2d3335",
              "primary-dim": "#005a74",
              "on-error": "#fff7f6",
              "surface-tint": "#006784",
              "on-primary-fixed": "#003545",
              "tertiary-dim": "#005e57",
              "on-primary-container": "#004a5f",
              "error-container": "#fa746f",
              "surface-container": "#ebeef0",
              "on-tertiary": "#e2fffa",
              "secondary": "#456370",
              "on-primary": "#f2faff",
              "inverse-primary": "#85d7f9",
              "on-secondary-fixed-variant": "#41606c",
              "tertiary-fixed-dim": "#71d7cd",
              "surface-bright": "#f8f9fa",
              "outline": "#767c7e",
              "secondary-fixed": "#c7e8f6",
              "secondary-dim": "#395764",
              "on-tertiary-container": "#00534d",
              "error": "#a83836",
              "surface-container-low": "#f1f4f5",
              "tertiary": "#006b64",
              "inverse-on-surface": "#9b9d9e",
              "on-tertiary-fixed-variant": "#005d57",
              "surface-variant": "#dee3e6",
              "secondary-fixed-dim": "#b9d9e8",
              "outline-variant": "#adb3b5",
              "inverse-surface": "#0c0f10",
              "tertiary-container": "#7fe6db",
              "primary": "#006784",
              "tertiary-fixed": "#7fe6db",
              "surface": "#f8f9fa",
              "surface-container-highest": "#dee3e6",
              "primary-fixed-dim": "#77c9eb"
          },
          "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
          },
          "fontFamily": {
              "headline": ["Manrope", "sans-serif"],
              "body": ["Public Sans", "sans-serif"],
              "label": ["Public Sans", "sans-serif"]
          }
      },
  },
  plugins: [],
}
